### ISSUE TITLE
pkg_resources removed in python 3.12

### ISSUE THREAD

**Issue by 2bndy5** [adafruit/circuitpython-build-tools#103]
Using python 3.12 to build bundles results in the following error:
```
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/circuitpython_build_tools/scripts/build_bundles.py", line 40, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

[`setuptools` has a migration guide](https://importlib-resources.readthedocs.io/en/latest/migration.html) (from `pkg_resources` to `importlib.resources`).

# Possible replacements

https://github.com/adafruit/circuitpython-build-tools/blob/9f02e3a1c9d017e6b76aac106efebf7d2b0c0b6d/circuitpython_build_tools/scripts/build_bundles.py#L271-L272
could be replaced with [the suggestion](https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename) from the aforementioned migration guide.

> [!NOTE]
> The above snippet seems to specifically support using Travis CI. Travis CI isn't used in CirPy CI workflows anymore, and they no longer have a free tier (maybe some customers were grandfathered into current pricing?).
>
> And then there's this (seemingly antiquated) statement in the README:
>>These build tools are intended for use with Travis CI

---
https://github.com/adafruit/circuitpython-build-tools/blob/9f02e3a1c9d017e6b76aac106efebf7d2b0c0b6d/circuitpython_build_tools/scripts/build_bundles.py#L247-L250
could be replaced with [`importlib_metadata.version()`](https://importlib-metadata.readthedocs.io/en/latest/api.html#importlib_metadata.version)

## TBC
I haven't delved into the impact of these changes, but I figure d I'd better open an issue to track this for future support of python 3.12.

**Comment by jepler** [comment]
can you put this in as a PR so that we can see what the CI thinks about the proposed change?

**Comment by jepler** [comment]
we don't use travis anymore for anything circuitpython related

**Comment by 2bndy5** [comment]
Should I remove that travis-specific code block? If so, I think the README should also be adjusted accordingly.

**Comment by jepler** [comment]
Correcting the README with current info would be good, but let's handle the pkg_resources problem separately from that.
