### ISSUE TITLE
Memento Camera Project Bundle not including library dependencies 

### ISSUE THREAD

**Issue by djecken** [adafruit/circuitpython-build-tools#112]
When testing the download project bundle from the fancy camera (https://learn.adafruit.com/adafruit-memento-camera-board/fancy-camera ) page on the memento learn guide, the zip file does not include all of the necessary libraries, only the adafruit_pycamera library is added.

**Comment by jepler** [comment]
Based on @BlitzCityDIY's comment and my own research, it seems this is a problem in circuitpython-build-tools. Most likely I introduced it in #110.

The fallout is that dependencies became listed in `e
