### ISSUE TITLE
Enable mpy-cross compilation of some/all __init__.py files in libraries

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/circuitpython-build-tools#29]
The current build system intentionally does not apply `mpy-cross` to `__init__.py` to produce a compiled `__init__.mpy`. I noticed this whilst checking the latest `adafruit_midi` library in the bundle as it blows up one of my programs with a `MemoryError` - I had previously been manually compiling all the **.py** files.

@sommersoft pointed me to the [relevant line in the build](https://github.com/adafruit/circuitpython-build-tools/blob/master/circuitpython_build_tools/build.py#L33) system, this is an intentional omission.

```
IGNORE_PY = ["setup.py", "conf.py", "__init__.py"]
```

In the absence of comments or other external information I'll speculate the purpose of this was to disable compilation for:

- `./setup.py` - pointless as it's not part of the library code
- `./docs/conf.py` - pointless (ditto)
- `__init__.py` - not sure here, this could be because many are 0 bytes and `mpy-cross` will make a bigger (!) .mpy - there's some [additional special casing hard-coded in too](https://github.com/adafruit/circuitpython-build-tools/blob/master/circuitpython_build_tools/build.py#L168).

There's some additional comments on this in https://github.com/adafruit/Adafruit_CircuitPython_MIDI/issues/3#issuecomment-487035082.

If my understanding of the functionality and exclusions here is correct this would be better implemetented as a fully pathed exclusion of `./setup.py` and `./docs/conf.py` and an _extra_ list of unpathed files to exclude from compilation if 0 bytes, or possibly a general rule of do not `mpy-cross` compile if less than or equal to XX bytes?

**Comment by kevinjwalters** [comment]
Quick survey of non-zero length `__init__.py` files from `adafruit-circuitpython-bundle-4.x-mpy-20190425` bundle:

```
adafruit_midi/__init__.py                           9186
adafruit_imageload/__init__.py                      2249
adafruit_bluefruit_connect/__in...                  1930
adafruit_ble/__init__.py                            1819
adafruit_hid/__init__.py                            1380
adafruit_thermal_printer/__init...                   982
adafruit_tinylora/__init__.py                        177
adafruit_rgb_display/__init__.py                     106
adafruit_apds9960/__init__.py                         43
```

**Comment by sommersoft** [comment]
So, after some deeper diving, I found that I pointed to the wrong block previously. The part that precludes `__init__.py` from mpy-cross is [here](https://github.com/adafruit/circuitpython-build-tools/blob/master/circuitpython_build_tools/build.py#L168), and looks like so:
```python
 if (not mpy_cross or
     os.stat(full_path).st_size == 0 or
     filename.endswith("__init__.py")):
                output_file = os.path.join(output_directory, filename)
                shutil.copyfile(temp_file.name, output_file)
```
This basically forces a straight file copy of the `.py`. Also, the above only applies to packaged libraries. With the `os.stat().st_size == 0` condition, I think it's safe to remove the `__init__.py` condition. I'll run some iterations. @kevinjwalters, I'll put up a version of a midi bundle in a few, if you wouldn't mind testing.

The previously cited `IGNORE_PY = ["setup.py", "conf.py", "__init__.py"]` only applies to un-packaged libraries, so can probably remain.

**Comment by sommersoft** [comment]
@kevinjwalters here's a whole bundle, with `__init__.py`s, mpy'd.

[test-4.x-mpy-2d7b358.zip](https://github.com/adafruit/circuitpython-build-tools/files/3136334/test-4.x-mpy-2d7b358.zip)

**Comment by kevinjwalters** [comment]
That bundle looks and works fine, I tried it on two CPX I've borrowed.

**Comment by kevinjwalters** [comment]
What's approximate ETA for getting this fix out there and what's likely to be the first bundle produced with this?

I ask because I'd like to know whether I need to include an interim step in a Learn guide to source `adafruit_midi` library from somewhere with compiled **mpy** before the official bundle arrives.

**Comment by kevinjwalters** [comment]
On a loosely-related note, the adafruit_midi library does't currently appear on https://circuitpython.readthedocs.io/en/latest/docs/drivers.html#adafruit-circuitpython-library-bundle - the page says its source is https://github.com/adafruit/Adafruit_CircuitPython_Bundle/blob/master/docs/index.rst which appears to use some sort of search/generated includes. How does the library get added to this page?

**Comment by kevinjwalters** [comment]
BTW, there's a tiny chance this was to deal with https://github.com/micropython/micropython/issues/2680 logged by @tdicola? That was quickly fixed and that may have actually been before **mpy** support was present in the official releases of micropython?

**Comment by sommersoft** [comment]
> What's approximate ETA for getting this fix out there and what's likely to be the first bundle produced with this?

With PyCon going on this week, I can't say for sure. I _could_ merge the PR, but I'd rather have it reviewed before that.

> On a loosely-related note, the adafruit_midi library does't currently appear on RTD

The entries are in the `/docs/drivers.rst` file. I can do up a PR real quick.

**Comment by sommersoft** [comment]
Actually, it looks like RTD was never setup for `adafruit_midi`; I can only find `usb_midi` from the core. I'll put up an issue for that.

**Comment by sommersoft** [comment]
PR #31 didn't work out well upon deployments to PyPI. So, it was reverted. Reopening this so it doesn't get lost...

**Comment by kevinjwalters** [comment]
Is this going out soon? I had a glance at 20190516 bundle and noticed (uncompiled) `__init__.py` was still in there.

**Comment by sommersoft** [comment]
@kevinjwalters apologies! After "re-fixing", the Travis YAML changes wouldn't trigger the PyPI deployment. PR to fix that is in, so hopefully this will be out soon.

**Comment by sommersoft** [comment]
This is now fully implemented. :phew:

@kevinjwalters you should be good to point at the latest bundle now. Though, still may be a good idea to give it a couple days to soak. I don't imagine anything breaking, but...i thought that before too. 😄
