### ISSUE TITLE
Fix Repo Artifacts in '/lib/'

### ISSUE THREAD

**Issue by sommersoft** [adafruit/circuitpython-build-tools#30]
A picture says a 1000 words:
![bundle_extra_folders PNG](https://user-images.githubusercontent.com/21211479/57051141-a77c5f80-6c45-11e9-8232-7c4d33419965.jpg)
________________________________________
`/lib/test/` is from Adafruit_CircuitPython_BitmapFont, and appears to be used by the example. There is a [PR](https://github.com/adafruit/Adafruit_CircuitPython_Bitmap_Font/pull/6) in to fix the example's import by pointing where folder is placed into the bundle.
![bundle_extra_folders_1 PNG](https://user-images.githubusercontent.com/21211479/57051204-04781580-6c46-11e9-9419-c52c93a37d1b.jpg)
________________________________________
`/lib/utils/` is from Adafruit_CircuitPython_framebuf.
![bundle_extra_folders_3 PNG](https://user-images.githubusercontent.com/21211479/57052738-e531b600-6c4e-11e9-908b-17628d90ed08.jpg)

________________________________________
`/lib/tests/` is from Adafruit_CircuitPython_MIDI, and are unit tests for the library. I'm fairly certain this should not be in the bundle.
![bundle_extra_folders_2 PNG](https://user-images.githubusercontent.com/21211479/57052734-dcd97b00-6c4e-11e9-8e41-a9fb4b9a91d1.jpg)

________________________________________
Here are my ideas on how to address these, and possibly handle future instances as these have started to crop up.

- [ ] `/lib/test/` & future: move the folder into BitmapFont's `examples` folder, so that it gets bundled there. For the future, we could start including all files in examples folders. We recently included one file specifically, but this is not a scaleable way to handle this.

- [ ] `/lib/utils/`: one of two things come to mind: 1) package-ize and move the contents there. 2) wait for `framebuf` to ride off into the sunset once `displayio` is fully implemented.

- [ ] `/lib/tests/` & future: these should be ignored, since they don't belong in the bundle. My first thought is to bolster the packaging code to only include folders that share the repo name (e.g. `Adafruit_CircuitPython_MIDI` will only include a package folder of `adafruit_midi`, by parsing the repo name.

**Comment by sommersoft** [comment]
PR #31 was reverted due to issues after deployments to PyPI. Reopening...

**Comment by kevinjwalters** [comment]
https://github.com/adafruit/Adafruit_CircuitPython_Motor has a tests directory for comparison

**Comment by sommersoft** [comment]
Forgot to re-close this a while ago...
