### ISSUE TITLE
The pypi_name is wrong in the JSON file

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/circuitpython-build-tools#67]
I've just noticed that the pypi_name is wrong in the .json release files. I've had a quick look but can't figure out the root cause.

Example:
Adafruit-CircuitPython-Display-Text
```json
{
  "adafruit_display_text": {
    "package": true,
    "pypi_name": "adafruit-circuitpython-display-",
    "version": "2.18.3",
    "repo": "https://github.com/adafruit/adafruit_circuitpython_display_text",
    "path": "lib/adafruit_display_text",
    "dependencies": [],
    "external_dependencies": []
  }
}
```

Adafruit-CircuitPython-DHT
```json
{
  "adafruit_dht": {
    "package": false,
    "pypi_name": "adafruit-circuitpython",
    "version": "3.6.0",
    "repo": "https://github.com/adafruit/adafruit_circuitpython_dht",
    "path": "lib/adafruit_dht",
    "dependencies": [],
    "external_dependencies": []
  }
}
```

**Comment by lesamouraipourpre** [comment]
A possible cause is Line 64:
https://github.com/adafruit/circuitpython-build-tools/blob/7b0b16d2be926b2a696086c149120bb6e478f18c/circuitpython_build_tools/scripts/build_bundles.py#L60-L65

This assumes that the repo will end with ".git" which is optional.
For example, 
`git clone https://github.com/adafruit/circuitpython-build-tools.git`
and
`git clone https://github.com/adafruit/circuitpython-build-tools`
are both valid.

**Comment by makermelissa** [comment]
Thanks, I didn't realize it was optional. That should be a fairly easy fix.
